version: "3.3"

services:

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    hostname: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ${PWD}/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    container_name: grafana
    hostname: grafana
    
    ports:
      - 3000:3000
    # volumes:
    #   - '$PWD/grafana_data:/var/lib/grafana'
  app:
    build:
      context: app
      dockerfile: Dockerfile
    depends_on:
      - prometheus
    ports:
      - "8080:8080"
